import Searchbar from "./Components/Searchbar";
import Title from "./Components/Title";
import SearchResults from "./[searchTerms]/page";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body className="overflow-hidden">
				<Title />
				<Searchbar />
				{children}
			</body>
		</html>
	);
}
